// Structured long-term curriculum map for EYFS (Ages 3-4 and 4-5)
export interface EYFSWeekPlan {
  term: string;
  week: number;
  theme: string;
  communication_language: string;
  psed: string;
  physical_development: string;
  literacy: string;
  mathematics: string;
  understanding_the_world: string;
  expressive_arts_design: string;
}

export const EYFS_NURSERY_PLAN: EYFSWeekPlan[] = [
  {
    "term": "Autumn",
    "week": 1,
    "theme": "Marvelous Me",
    "communication_language": "Talk about self",
    "psed": "Build confidence",
    "physical_development": "Body movements",
    "literacy": "Name recognition",
    "mathematics": "Count to 3",
    "understanding_the_world": "Body parts",
    "expressive_arts_design": "Self-portraits"
  },
  {
    "term": "Autumn",
    "week": 2,
    "theme": "Family",
    "communication_language": "Discuss family members",
    "psed": "Sense of belonging",
    "physical_development": "Fine motor collage",
    "literacy": "Family stories",
    "mathematics": "Sorting family groups",
    "understanding_the_world": "Family similarities",
    "expressive_arts_design": "Family role play"
  },
  {
    "term": "Autumn",
    "week": 3,
    "theme": "People Who Help Us",
    "communication_language": "Introduce occupations",
    "psed": "Respect others",
    "physical_development": "Tool manipulation",
    "literacy": "Story sequencing",
    "mathematics": "Count objects",
    "understanding_the_world": "Community awareness",
    "expressive_arts_design": "Role-play stations"
  },
  {
    "term": "Autumn",
    "week": 4,
    "theme": "Colours Everywhere",
    "communication_language": "Colour vocabulary",
    "psed": "Share resources",
    "physical_development": "Colour sorting",
    "literacy": "Colour books",
    "mathematics": "Match colours",
    "understanding_the_world": "Colours in environment",
    "expressive_arts_design": "Painting"
  },
  {
    "term": "Autumn",
    "week": 5,
    "theme": "Shapes & Patterns",
    "communication_language": "Shape language",
    "psed": "Cooperative play",
    "physical_development": "Shape tracing",
    "literacy": "Shape stories",
    "mathematics": "Identify basic shapes",
    "understanding_the_world": "Shape hunt",
    "expressive_arts_design": "Printing patterns"
  },
  {
    "term": "Autumn",
    "week": 6,
    "theme": "Weather Wonders",
    "communication_language": "Describe weather",
    "psed": "Express feelings",
    "physical_development": "Outdoor exploration",
    "literacy": "Weather vocabulary",
    "mathematics": "Compare sizes",
    "understanding_the_world": "Observe weather",
    "expressive_arts_design": "Weather art"
  },
  {
    "term": "Autumn",
    "week": 7,
    "theme": "Seasons",
    "communication_language": "Seasonal discussions",
    "psed": "Adapt to change",
    "physical_development": "Nature walks",
    "literacy": "Seasonal stories",
    "mathematics": "Sorting objects",
    "understanding_the_world": "Seasonal changes",
    "expressive_arts_design": "Leaf printing"
  },
  {
    "term": "Autumn",
    "week": 8,
    "theme": "Animals Around Us",
    "communication_language": "Animal names",
    "psed": "Caring for living things",
    "physical_development": "Animal movement",
    "literacy": "Animal stories",
    "mathematics": "Count animals",
    "understanding_the_world": "Habitats",
    "expressive_arts_design": "Animal masks"
  },
  {
    "term": "Autumn",
    "week": 9,
    "theme": "Fruits",
    "communication_language": "Describe fruits",
    "psed": "Healthy choices",
    "physical_development": "Cutting skills",
    "literacy": "Fruit books",
    "mathematics": "Sorting fruits",
    "understanding_the_world": "Healthy foods",
    "expressive_arts_design": "Fruit printing"
  },
  {
    "term": "Autumn",
    "week": 10,
    "theme": "Transportation",
    "communication_language": "Vehicle vocabulary",
    "psed": "Taking turns",
    "physical_development": "Gross motor travel games",
    "literacy": "Transport stories",
    "mathematics": "Count wheels",
    "understanding_the_world": "Types of transport",
    "expressive_arts_design": "Junk modelling"
  },
  {
    "term": "Autumn",
    "week": 11,
    "theme": "Celebrations",
    "communication_language": "Talk about events",
    "psed": "Respect diversity",
    "physical_development": "Dance activities",
    "literacy": "Celebration stories",
    "mathematics": "Counting candles",
    "understanding_the_world": "Family traditions",
    "expressive_arts_design": "Celebration crafts"
  },
  {
    "term": "Autumn",
    "week": 12,
    "theme": "Festivals",
    "communication_language": "Learn cultural vocabulary",
    "psed": "Respect differences",
    "physical_development": "Festival games",
    "literacy": "Festival books",
    "mathematics": "Pattern making",
    "understanding_the_world": "Different cultures",
    "expressive_arts_design": "Festival art"
  },
  {
    "term": "Spring",
    "week": 1,
    "theme": "Once Upon a Time",
    "communication_language": "Listen and join in repeated story phrases",
    "psed": "Develop confidence speaking in groups",
    "physical_development": "Fine motor activities using story characters",
    "literacy": "Enjoy traditional tales and picture books",
    "mathematics": "Compare big, medium and small",
    "understanding_the_world": "Explore characters and settings",
    "expressive_arts_design": "Create crowns, castles and puppets"
  },
  {
    "term": "Spring",
    "week": 2,
    "theme": "Super Space",
    "communication_language": "Learn and use space vocabulary",
    "psed": "Build curiosity and confidence",
    "physical_development": "Move like astronauts",
    "literacy": "Listen to space stories and discuss pictures",
    "mathematics": "Count stars and rockets to 5",
    "understanding_the_world": "Explore day and night",
    "expressive_arts_design": "Design rockets and planets"
  },
  {
    "term": "Spring",
    "week": 3,
    "theme": "Health Heroes",
    "communication_language": "Talk about healthy habits",
    "psed": "Learn self-care routines",
    "physical_development": "Practise handwashing and tooth-brushing",
    "literacy": "Learn health-related vocabulary",
    "mathematics": "Count healthy foods",
    "understanding_the_world": "Learn about keeping healthy",
    "expressive_arts_design": "Create healthy eating collages"
  },
  {
    "term": "Spring",
    "week": 4,
    "theme": "Minibeasts",
    "communication_language": "Describe insects and bugs",
    "psed": "Show care for living things",
    "physical_development": "Develop pincer grip through bug hunts",
    "literacy": "Enjoy stories about insects",
    "mathematics": "Count spots, legs and wings",
    "understanding_the_world": "Explore habitats and life cycles",
    "expressive_arts_design": "Make caterpillars and butterflies"
  },
  {
    "term": "Spring",
    "week": 5,
    "theme": "Growing and Changing",
    "communication_language": "Discuss changes in plants and people",
    "psed": "Develop responsibility through plant care",
    "physical_development": "Digging, planting and watering activities",
    "literacy": "Learn new vocabulary linked to growth",
    "mathematics": "Measure plants using simple language",
    "understanding_the_world": "Observe growth and change",
    "expressive_arts_design": "Flower printing and nature collages"
  },
  {
    "term": "Spring",
    "week": 6,
    "theme": "Water Wonders",
    "communication_language": "Describe water play experiences",
    "psed": "Cooperate during investigations",
    "physical_development": "Pouring, filling and transferring water",
    "literacy": "Listen to stories involving water",
    "mathematics": "Explore full, empty and half full",
    "understanding_the_world": "Investigate floating and sinking",
    "expressive_arts_design": "Water painting and bubble art"
  },
  {
    "term": "Spring",
    "week": 7,
    "theme": "Around the World",
    "communication_language": "Learn words from different cultures",
    "psed": "Respect similarities and differences",
    "physical_development": "Explore cultural dances and movements",
    "literacy": "Listen to stories from different countries",
    "mathematics": "Compare sizes and quantities",
    "understanding_the_world": "Explore homes, foods and clothing worldwide",
    "expressive_arts_design": "Create cultural art and flags"
  },
  {
    "term": "Spring",
    "week": 8,
    "theme": "Dinosaurs",
    "communication_language": "Use descriptive language to talk about dinosaurs",
    "psed": "Work together during investigations",
    "physical_development": "Digging and excavation activities",
    "literacy": "Enjoy dinosaur stories and rhymes",
    "mathematics": "Count dinosaur eggs and footprints",
    "understanding_the_world": "Learn about creatures from long ago",
    "expressive_arts_design": "Create dinosaur models and fossils"
  },
  {
    "term": "Spring",
    "week": 9,
    "theme": "Books Week",
    "communication_language": "Retell favourite stories",
    "psed": "Build confidence sharing books",
    "physical_development": "Develop book-handling skills",
    "literacy": "Foster a love of reading",
    "mathematics": "Count story characters and objects",
    "understanding_the_world": "Learn about authors and illustrators",
    "expressive_arts_design": "Create story props and puppets"
  },
  {
    "term": "Spring",
    "week": 10,
    "theme": "Vegetables",
    "communication_language": "Name and describe vegetables",
    "psed": "Develop healthy food choices",
    "physical_development": "Practise cutting and food preparation skills",
    "literacy": "Listen to stories about vegetables",
    "mathematics": "Sort vegetables by size and colour",
    "understanding_the_world": "Learn how vegetables grow",
    "expressive_arts_design": "Vegetable printing and food art"
  },
  {
    "term": "Summer",
    "week": 1,
    "theme": "Foods We Eat",
    "communication_language": "Talk about favourite foods and healthy choices",
    "psed": "Develop independence during snack routines",
    "physical_development": "Practise spreading, pouring and using utensils",
    "literacy": "Listen to food stories and learn food vocabulary",
    "mathematics": "Sort foods by colour, type and size",
    "understanding_the_world": "Explore where food comes from",
    "expressive_arts_design": "Fruit and vegetable printing"
  },
  {
    "term": "Summer",
    "week": 2,
    "theme": "Under the Sea",
    "communication_language": "Learn names of sea creatures",
    "psed": "Show care for living things",
    "physical_development": "Move like sea animals",
    "literacy": "Join in repeated story phrases",
    "mathematics": "Count fish and sea creatures",
    "understanding_the_world": "Explore ocean habitats",
    "expressive_arts_design": "Create ocean collages and sea creature models"
  },
  {
    "term": "Summer",
    "week": 3,
    "theme": "Jungle Adventures",
    "communication_language": "Describe jungle animals using new vocabulary",
    "psed": "Work cooperatively during role play",
    "physical_development": "Develop balance through jungle movement activities",
    "literacy": "Enjoy rhyming jungle stories",
    "mathematics": "Compare sizes of jungle animals",
    "understanding_the_world": "Learn about rainforest habitats",
    "expressive_arts_design": "Make animal masks and jungle art"
  },
  {
    "term": "Summer",
    "week": 4,
    "theme": "Music and Rhythm",
    "communication_language": "Listen and respond to different sounds",
    "psed": "Build confidence performing with others",
    "physical_development": "Develop coordination through dance and movement",
    "literacy": "Enjoy musical stories and rhymes",
    "mathematics": "Explore repeating patterns and beats",
    "understanding_the_world": "Investigate sounds and instruments",
    "expressive_arts_design": "Create music using instruments"
  },
  {
    "term": "Summer",
    "week": 5,
    "theme": "Sports and Games",
    "communication_language": "Follow simple instructions and rules",
    "psed": "Learn teamwork and turn-taking",
    "physical_development": "Develop running, jumping and balancing skills",
    "literacy": "Listen to sports stories",
    "mathematics": "Count scores and equipment",
    "understanding_the_world": "Learn about exercise and healthy bodies",
    "expressive_arts_design": "Design medals and team flags"
  },
  {
    "term": "Summer",
    "week": 6,
    "theme": "Pirates and Explorers",
    "communication_language": "Use adventurous vocabulary in role play",
    "psed": "Build confidence through imaginative play",
    "physical_development": "Develop coordination through obstacle courses",
    "literacy": "Explore treasure maps and symbols",
    "mathematics": "Use positional language",
    "understanding_the_world": "Learn about journeys and maps",
    "expressive_arts_design": "Construct pirate ships and treasure maps"
  },
  {
    "term": "Summer",
    "week": 7,
    "theme": "Weather Explorers",
    "communication_language": "Describe daily weather changes",
    "psed": "Develop curiosity about nature",
    "physical_development": "Outdoor investigations and movement",
    "literacy": "Explore weather-related vocabulary",
    "mathematics": "Compare rainfall, size of puddles and temperatures",
    "understanding_the_world": "Observe weather patterns",
    "expressive_arts_design": "Create weather collages and paintings"
  },
  {
    "term": "Summer",
    "week": 8,
    "theme": "Summer Festivals",
    "communication_language": "Talk about celebrations and traditions",
    "psed": "Respect similarities and differences",
    "physical_development": "Participate in cultural dances and games",
    "literacy": "Listen to festival stories",
    "mathematics": "Count and create patterns",
    "understanding_the_world": "Explore different celebrations",
    "expressive_arts_design": "Festival crafts and music"
  },
  {
    "term": "Summer",
    "week": 9,
    "theme": "Amazing Creatures Revision",
    "communication_language": "Recall facts about animals studied during the year",
    "psed": "Show care and responsibility towards animals",
    "physical_development": "Animal movement activities",
    "literacy": "Retell favourite animal stories",
    "mathematics": "Sort animals by features and habitats",
    "understanding_the_world": "Compare animals and their environments",
    "expressive_arts_design": "Create animal models and artwork"
  },
  {
    "term": "Summer",
    "week": 10,
    "theme": "Our Wonderful World",
    "communication_language": "Discuss the world around us",
    "psed": "Develop appreciation for nature",
    "physical_development": "Participate in outdoor exploration",
    "literacy": "Listen to stories about the Earth",
    "mathematics": "Count and sort natural objects",
    "understanding_the_world": "Learn about recycling and caring for the environment",
    "expressive_arts_design": "Create recycled art"
  },
  {
    "term": "Summer",
    "week": 11,
    "theme": "Ready for School",
    "communication_language": "Talk about moving to Reception",
    "psed": "Build confidence and independence",
    "physical_development": "Practise dressing and self-care skills",
    "literacy": "Share favourite stories and experiences",
    "mathematics": "Review counting and shape knowledge",
    "understanding_the_world": "Explore new classroom routines",
    "expressive_arts_design": "Create transition memory books"
  },
  {
    "term": "Summer",
    "week": 12,
    "theme": "Graduation & Achievement",
    "communication_language": "Reflect on favourite learning experiences",
    "psed": "Celebrate achievements and friendships",
    "physical_development": "Participate in sports and celebration activities",
    "literacy": "Review favourite books and rhymes",
    "mathematics": "Review mathematical concepts learned",
    "understanding_the_world": "Reflect on growth and learning journey",
    "expressive_arts_design": "Graduation performances and crafts"
  }
];

export const EYFS_RECEPTION_PLAN: EYFSWeekPlan[] = [
  {
    "term": "Autumn",
    "week": 1,
    "theme": "Marvelous Me",
    "communication_language": "Extended conversations",
    "psed": "Self-awareness",
    "physical_development": "Controlled movements",
    "literacy": "Write own name",
    "mathematics": "Numbers to 10",
    "understanding_the_world": "Personal history",
    "expressive_arts_design": "Detailed self-portraits"
  },
  {
    "term": "Autumn",
    "week": 2,
    "theme": "Family",
    "communication_language": "Explain relationships",
    "psed": "Respect family diversity",
    "physical_development": "Fine motor control",
    "literacy": "Family captions",
    "mathematics": "Comparing quantities",
    "understanding_the_world": "Family traditions",
    "expressive_arts_design": "Family models"
  },
  {
    "term": "Autumn",
    "week": 3,
    "theme": "People Who Help Us",
    "communication_language": "Ask and answer questions",
    "psed": "Community responsibility",
    "physical_development": "Writing tools control",
    "literacy": "Labels and signs",
    "mathematics": "Counting beyond 10",
    "understanding_the_world": "Community roles",
    "expressive_arts_design": "Role-play scenarios"
  },
  {
    "term": "Autumn",
    "week": 4,
    "theme": "Colours Everywhere",
    "communication_language": "Descriptive language",
    "psed": "Confidence sharing ideas",
    "physical_development": "Precision painting",
    "literacy": "Colour words",
    "mathematics": "Sorting rules",
    "understanding_the_world": "Colour investigations",
    "expressive_arts_design": "Mixed-media art"
  },
  {
    "term": "Autumn",
    "week": 5,
    "theme": "Shapes & Patterns",
    "communication_language": "Mathematical language",
    "psed": "Collaborative learning",
    "physical_development": "Shape construction",
    "literacy": "Shape captions",
    "mathematics": "2D and 3D shapes",
    "understanding_the_world": "Shapes in environment",
    "expressive_arts_design": "Pattern design"
  },
  {
    "term": "Autumn",
    "week": 6,
    "theme": "Weather Wonders",
    "communication_language": "Predict and explain",
    "psed": "Resilience",
    "physical_development": "Outdoor challenges",
    "literacy": "Weather reports",
    "mathematics": "Measuring",
    "understanding_the_world": "Weather recording",
    "expressive_arts_design": "Weather collage"
  },
  {
    "term": "Autumn",
    "week": 7,
    "theme": "Seasons",
    "communication_language": "Discuss change over time",
    "psed": "Adaptability",
    "physical_development": "Outdoor exploration",
    "literacy": "Seasonal writing",
    "mathematics": "Sequencing",
    "understanding_the_world": "Seasonal science",
    "expressive_arts_design": "Nature art"
  },
  {
    "term": "Autumn",
    "week": 8,
    "theme": "Animals Around Us",
    "communication_language": "Explain observations",
    "psed": "Caring attitudes",
    "physical_development": "Movement control",
    "literacy": "Animal fact files",
    "mathematics": "Comparing quantities",
    "understanding_the_world": "Habitats",
    "expressive_arts_design": "Animal sculptures"
  },
  {
    "term": "Autumn",
    "week": 9,
    "theme": "Fruits",
    "communication_language": "Healthy discussions",
    "psed": "Healthy choices",
    "physical_development": "Food preparation",
    "literacy": "Instructions",
    "mathematics": "Weighing",
    "understanding_the_world": "Food origins",
    "expressive_arts_design": "Food art"
  },
  {
    "term": "Autumn",
    "week": 10,
    "theme": "Transportation",
    "communication_language": "Comparative language",
    "psed": "Teamwork",
    "physical_development": "Obstacle courses",
    "literacy": "Information texts",
    "mathematics": "Position language",
    "understanding_the_world": "Travel past and present",
    "expressive_arts_design": "Vehicle models"
  },
  {
    "term": "Autumn",
    "week": 11,
    "theme": "Celebrations",
    "communication_language": "Retelling experiences",
    "psed": "Cultural awareness",
    "physical_development": "Dance and movement",
    "literacy": "Invitations",
    "mathematics": "Counting and patterns",
    "understanding_the_world": "Cultural traditions",
    "expressive_arts_design": "Celebration projects"
  },
  {
    "term": "Autumn",
    "week": 12,
    "theme": "Festivals",
    "communication_language": "Discuss similarities/differences",
    "psed": "Respect for diversity",
    "physical_development": "Festival games",
    "literacy": "Festival recounts",
    "mathematics": "Pattern work",
    "understanding_the_world": "World cultures",
    "expressive_arts_design": "Festival crafts"
  },
  {
    "term": "Spring",
    "week": 1,
    "theme": "Once Upon a Time",
    "communication_language": "Retell familiar stories using story language",
    "psed": "Build confidence speaking in groups",
    "physical_development": "Develop fine motor control through story crafts",
    "literacy": "Sequence stories and write simple captions",
    "mathematics": "Compare and order by size",
    "understanding_the_world": "Explore traditional tales from different cultures",
    "expressive_arts_design": "Create castles, crowns and puppets"
  },
  {
    "term": "Spring",
    "week": 2,
    "theme": "Super Space",
    "communication_language": "Ask and answer questions about space",
    "psed": "Develop curiosity and resilience",
    "physical_development": "Astronaut movement challenges",
    "literacy": "Write labels for planets and rockets",
    "mathematics": "Count, compare and order numbers to 10",
    "understanding_the_world": "Investigate day/night and the solar system",
    "expressive_arts_design": "Design rockets and planets"
  },
  {
    "term": "Spring",
    "week": 3,
    "theme": "Health Heroes",
    "communication_language": "Explain healthy choices using appropriate vocabulary",
    "psed": "Develop independence in self-care",
    "physical_development": "Practise hygiene routines and obstacle courses",
    "literacy": "Write healthy food lists and labels",
    "mathematics": "Compare quantities and create simple charts",
    "understanding_the_world": "Learn about healthy lifestyles",
    "expressive_arts_design": "Create healthy meal collages"
  },
  {
    "term": "Spring",
    "week": 4,
    "theme": "Minibeasts",
    "communication_language": "Describe life cycles and habitats",
    "psed": "Show care and respect for living things",
    "physical_development": "Develop dexterity through bug-themed activities",
    "literacy": "Write minibeast fact cards",
    "mathematics": "Count legs, spots and wings",
    "understanding_the_world": "Investigate life cycles and habitats",
    "expressive_arts_design": "Create minibeast models"
  },
  {
    "term": "Spring",
    "week": 5,
    "theme": "Growing and Changing",
    "communication_language": "Use language to describe growth and change",
    "psed": "Build responsibility through plant care",
    "physical_development": "Develop hand strength through planting activities",
    "literacy": "Record observations and label plant parts",
    "mathematics": "Measure growth using non-standard units",
    "understanding_the_world": "Investigate plant life cycles",
    "expressive_arts_design": "Create flower paintings and collages"
  },
  {
    "term": "Spring",
    "week": 6,
    "theme": "Water Wonders",
    "communication_language": "Predict and explain observations",
    "psed": "Cooperate during investigations",
    "physical_development": "Develop coordination through water play",
    "literacy": "Create simple experiment records",
    "mathematics": "Compare capacity and volume",
    "understanding_the_world": "Explore floating, sinking and water movement",
    "expressive_arts_design": "Watercolour artwork"
  },
  {
    "term": "Spring",
    "week": 7,
    "theme": "Around the World",
    "communication_language": "Discuss similarities and differences between countries",
    "psed": "Develop respect for diversity",
    "physical_development": "Learn cultural dances and games",
    "literacy": "Write postcards and simple sentences",
    "mathematics": "Explore positional language and maps",
    "understanding_the_world": "Investigate countries, cultures and traditions",
    "expressive_arts_design": "Create cultural artwork"
  },
  {
    "term": "Spring",
    "week": 8,
    "theme": "Dinosaurs",
    "communication_language": "Use descriptive language to discuss dinosaurs",
    "psed": "Work collaboratively in investigations",
    "physical_development": "Develop gross motor skills through dinosaur movement",
    "literacy": "Write dinosaur fact files",
    "mathematics": "Compare sizes, weights and lengths",
    "understanding_the_world": "Explore past and present",
    "expressive_arts_design": "Create fossils and dinosaur models"
  },
  {
    "term": "Spring",
    "week": 9,
    "theme": "Books Week",
    "communication_language": "Discuss favourite books and authors",
    "psed": "Develop confidence sharing opinions",
    "physical_development": "Handle books correctly and independently",
    "literacy": "Retell stories and write captions",
    "mathematics": "Count characters and objects in stories",
    "understanding_the_world": "Learn about authors and illustrators",
    "expressive_arts_design": "Create story props and puppets"
  },
  {
    "term": "Spring",
    "week": 10,
    "theme": "Vegetables",
    "communication_language": "Explain healthy eating choices",
    "psed": "Develop positive attitudes towards healthy foods",
    "physical_development": "Chop, peel and prepare vegetables safely",
    "literacy": "Write recipes and labels",
    "mathematics": "Sort, classify and compare vegetables",
    "understanding_the_world": "Investigate how vegetables grow",
    "expressive_arts_design": "Vegetable printing and food art"
  },
  {
    "term": "Spring",
    "week": 1,
    "theme": "Goldilocks and the Three Bears",
    "communication_language": "The Three Little Pigs",
    "psed": "2",
    "physical_development": "Whatever Next!",
    "literacy": "How to Catch a Star",
    "mathematics": "3",
    "understanding_the_world": "Topsy and Tim Go to the Doctor",
    "expressive_arts_design": "Funnybones"
  },
  {
    "term": "Spring",
    "week": 4,
    "theme": "The Very Hungry Caterpillar",
    "communication_language": "Mad About Minibeasts!",
    "psed": "5",
    "physical_development": "Jasper's Beanstalk",
    "literacy": "Jack and the Beanstalk",
    "mathematics": "6",
    "understanding_the_world": "Mr Gumpy's Outing",
    "expressive_arts_design": "Who Sank the Boat?"
  },
  {
    "term": "Spring",
    "week": 7,
    "theme": "We're All Wonders",
    "communication_language": "This Is How We Do It",
    "psed": "8",
    "physical_development": "Harry and the Bucketful of Dinosaurs",
    "literacy": "Dinosaur Roar!",
    "mathematics": "9",
    "understanding_the_world": "We're Going on a Bear Hunt",
    "expressive_arts_design": "The Gruffalo"
  },
  {
    "term": "Spring",
    "week": 10,
    "theme": "Oliver's Vegetables",
    "communication_language": "Supertato",
    "psed": "SONGS AND RHYMES",
    "physical_development": "Week",
    "literacy": "Song",
    "mathematics": "Once Upon a Time",
    "understanding_the_world": "Fairy Tale Action Song",
    "expressive_arts_design": "Super Space"
  },
  {
    "term": "Spring",
    "week": 1,
    "theme": "Comparing size and ordering objects",
    "communication_language": "2",
    "psed": "Counting, numeral recognition to 10",
    "physical_development": "3",
    "literacy": "Data handling and comparing quantities",
    "mathematics": "4",
    "understanding_the_world": "Counting, sorting and grouping",
    "expressive_arts_design": "5"
  },
  {
    "term": "Spring",
    "week": 6,
    "theme": "Capacity and volume",
    "communication_language": "7",
    "psed": "Positional language and mapping",
    "physical_development": "8",
    "literacy": "Comparing length, height and weight",
    "mathematics": "9",
    "understanding_the_world": "Number stories and sequencing",
    "expressive_arts_design": "10"
  },
  {
    "term": "Summer",
    "week": 1,
    "theme": "Foods We Eat",
    "communication_language": "Discuss healthy choices and food groups",
    "psed": "Make healthy decisions",
    "physical_development": "Use tools safely for food preparation",
    "literacy": "Write labels and simple food lists",
    "mathematics": "Compare quantities and weights",
    "understanding_the_world": "Learn where food comes from",
    "expressive_arts_design": "Design healthy meal plates"
  },
  {
    "term": "Summer",
    "week": 2,
    "theme": "Under the Sea",
    "communication_language": "Describe marine animals using new vocabulary",
    "psed": "Respect living things",
    "physical_development": "Develop coordination through movement games",
    "literacy": "Create sea creature fact cards",
    "mathematics": "Count, sort and compare sea creatures",
    "understanding_the_world": "Explore ocean habitats",
    "expressive_arts_design": "Create ocean collages"
  },
  {
    "term": "Summer",
    "week": 3,
    "theme": "Jungle Adventures",
    "communication_language": "Retell jungle stories and adventures",
    "psed": "Work collaboratively",
    "physical_development": "Move like jungle animals",
    "literacy": "Write captions for jungle scenes",
    "mathematics": "Explore patterns and sequencing",
    "understanding_the_world": "Learn about rainforests",
    "expressive_arts_design": "Create jungle artwork"
  },
  {
    "term": "Summer",
    "week": 4,
    "theme": "Music and Rhythm",
    "communication_language": "Discuss sounds and musical preferences",
    "psed": "Build confidence performing",
    "physical_development": "Develop rhythm and coordination",
    "literacy": "Create song lyrics and labels",
    "mathematics": "Explore repeating patterns",
    "understanding_the_world": "Investigate musical instruments",
    "expressive_arts_design": "Compose and perform music"
  },
  {
    "term": "Summer",
    "week": 5,
    "theme": "Sports and Games",
    "communication_language": "Explain rules and strategies",
    "psed": "Demonstrate teamwork",
    "physical_development": "Improve balance, agility and coordination",
    "literacy": "Record sports results using marks and symbols",
    "mathematics": "Compare scores and quantities",
    "understanding_the_world": "Learn about different sports",
    "expressive_arts_design": "Design team flags and medals"
  },
  {
    "term": "Summer",
    "week": 6,
    "theme": "Pirates and Explorers",
    "communication_language": "Use adventurous vocabulary",
    "psed": "Cooperate during group challenges",
    "physical_development": "Navigate obstacle courses",
    "literacy": "Create treasure maps and captions",
    "mathematics": "Use positional language",
    "understanding_the_world": "Explore maps and journeys",
    "expressive_arts_design": "Build pirate ships"
  },
  {
    "term": "Summer",
    "week": 7,
    "theme": "Weather Explorers",
    "communication_language": "Predict and describe weather changes",
    "psed": "Develop resilience and curiosity",
    "physical_development": "Outdoor investigations",
    "literacy": "Write simple weather reports",
    "mathematics": "Measure and record weather",
    "understanding_the_world": "Observe weather patterns",
    "expressive_arts_design": "Weather-themed art"
  },
  {
    "term": "Summer",
    "week": 8,
    "theme": "Summer Festivals",
    "communication_language": "Discuss traditions and celebrations",
    "psed": "Respect cultural differences",
    "physical_development": "Participate in dances and games",
    "literacy": "Create invitations and cards",
    "mathematics": "Explore patterns in festival designs",
    "understanding_the_world": "Learn about festivals around the world",
    "expressive_arts_design": "Festival crafts and performances"
  },
  {
    "term": "Summer",
    "week": 9,
    "theme": "Amazing Creatures",
    "communication_language": "Compare animal features and habitats",
    "psed": "Care for living things",
    "physical_development": "Animal movement activities",
    "literacy": "Create animal fact files",
    "mathematics": "Sort animals using criteria",
    "understanding_the_world": "Learn about animal adaptations",
    "expressive_arts_design": "Animal masks and models"
  },
  {
    "term": "Summer",
    "week": 10,
    "theme": "Our Wonderful World",
    "communication_language": "Discuss environmental issues",
    "psed": "Develop responsibility",
    "physical_development": "Participate in environmental projects",
    "literacy": "Create posters and messages",
    "mathematics": "Collect and interpret simple data",
    "understanding_the_world": "Learn about sustainability",
    "expressive_arts_design": "Recycled art projects"
  },
  {
    "term": "Summer",
    "week": 11,
    "theme": "Ready for Year 1",
    "communication_language": "Discuss hopes and expectations",
    "psed": "Build confidence for transition",
    "physical_development": "Develop independence skills",
    "literacy": "Write about favourite memories",
    "mathematics": "Consolidate number knowledge",
    "understanding_the_world": "Explore similarities and differences between Nursery and Year 1",
    "expressive_arts_design": "Create memory books"
  },
  {
    "term": "Summer",
    "week": 12,
    "theme": "Graduation & Achievement",
    "communication_language": "Reflect on learning experiences",
    "psed": "Celebrate achievements",
    "physical_development": "Participate in performances",
    "literacy": "Create graduation messages",
    "mathematics": "Review mathematical learning",
    "understanding_the_world": "Reflect on personal growth",
    "expressive_arts_design": "Graduation crafts and performances"
  }
];
